# Generated by Django 5.2.5 on 2025-09-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
