# Generated by Django 5.2.5 on 2025-09-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
