# Generated by Django 5.2.5 on 2025-09-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_article_author_alter_article_judul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug_art',
            field=models.SlugField(blank=True, editable=False, max_length=400),
        ),
    ]
