# Generated by Django 5.2.5 on 2025-09-08 04:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_article_slug_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='isi',
            field=tinymce.models.HTMLField(),
        ),
    ]
