# Generated by Django 5.2.5 on 2025-09-08 04:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_article_isi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='isi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
