# Generated by Django 5.2.5 on 2025-09-12 06:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_article_isi'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='share_count',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Thumbnail'),
        ),
    ]
