# Generated by Django 5.2.5 on 2025-09-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_articletag_remove_article_tag_taggedarticle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedarticle',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='core.articletag'),
        ),
    ]
