# Generated by Django 5.2.5 on 2025-09-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_taggedarticle_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('N', 'Normal'), ('A', 'Ads')], max_length=100),
        ),
    ]
