# Generated by Django 5.2.5 on 2025-09-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Ads', 'Ads')], default='N', max_length=100),
        ),
    ]
