# Generated by Django 5.2.5 on 2025-09-19 07:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_article_status_alter_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iklan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('durasi', models.IntegerField(max_length=365)),
                ('ads_potrait', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Thumbnail')),
                ('ads_landscape', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Thumbnail')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Ads', 'Ads')], default='Normal', max_length=100),
        ),
    ]
