# Generated by Django 5.2.5 on 2025-09-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_iklan_iklanredirect_alter_article_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidarticle',
            name='type',
            field=models.CharField(blank=True, default='Normal', max_length=100),
        ),
    ]
