# Generated by Django 5.2.5 on 2025-09-02 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='-', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('-', '-'), ('M', 'Pria'), ('F', 'Wanita')], default='-', max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('-', '-'), ('single', 'Tidak kawin'), ('married', 'Kawin'), ('private', 'Private')], default='-', max_length=10)),
                ('address', models.CharField(blank=True, default='-', max_length=255)),
                ('province', models.CharField(blank=True, default='-', max_length=100)),
                ('city', models.CharField(blank=True, default='-', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='-', max_length=10)),
                ('last_education', models.CharField(blank=True, choices=[('-', '-'), ('tidak_sekolah', 'Tidak/Belum Sekolah'), ('sd', 'SD / Sederajat'), ('smp', 'SMP / Sederajat'), ('sma', 'SMA / Sederajat'), ('diploma1', 'Diploma 1 (D1)'), ('diploma2', 'Diploma 2 (D2)'), ('diploma3', 'Diploma 3 (D3)'), ('sarjana', 'Sarjana (S1)'), ('magister', 'Magister (S2)'), ('doktor', 'Doktor (S3)')], default='-', max_length=20)),
                ('occupation', models.CharField(blank=True, choices=[('-', '-'), ('tidak_sekolah', 'Tidak/Belum Sekolah'), ('sd', 'SD / Sederajat'), ('smp', 'SMP / Sederajat'), ('sma', 'SMA / Sederajat'), ('diploma1', 'Diploma 1 (D1)'), ('diploma2', 'Diploma 2 (D2)'), ('diploma3', 'Diploma 3 (D3)'), ('sarjana', 'Sarjana (S1)'), ('magister', 'Magister (S2)'), ('doktor', 'Doktor (S3)')], default='-', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
