# Generated by Django 5.2.5 on 2025-09-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='alamat',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='postal_code',
            new_name='kode_pos',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='kota',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='nomor_telpon',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='occupation',
            new_name='pekerjaan',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_education',
            new_name='pendidikan_terakhir',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='province',
            new_name='provinsi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='marital_status',
            new_name='status_pernikahan',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='tanggal_lahir',
        ),
    ]
