# Generated by Django 5.2.5 on 2025-09-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_address_profile_alamat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nomor_telpon',
            new_name='nomor_handphone',
        ),
    ]
