# Generated by Django 5.2.5 on 2025-09-04 02:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_imagemanager_alter_profile_pekerjaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_profil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
