# Generated by Django 5.2.5 on 2025-09-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_foto_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageManager',
        ),
    ]
